# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(554, 507)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Plus_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Plus_Button.setGeometry(QtCore.QRect(30, 360, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Plus_Button.setFont(font)
        self.Plus_Button.setObjectName("Plus_Button")
        self.Minus_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Minus_Button.setGeometry(QtCore.QRect(150, 360, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Minus_Button.setFont(font)
        self.Minus_Button.setObjectName("Minus_Button")
        self.Multiply_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Multiply_Button.setGeometry(QtCore.QRect(270, 360, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Multiply_Button.setFont(font)
        self.Multiply_Button.setObjectName("Multiply_Button")
        self.Divide_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Divide_Button.setGeometry(QtCore.QRect(390, 360, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Divide_Button.setFont(font)
        self.Divide_Button.setObjectName("Divide_Button")
        self.Screen_3 = QtWidgets.QLabel(self.centralwidget)
        self.Screen_3.setGeometry(QtCore.QRect(30, 190, 481, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Screen_3.setFont(font)
        self.Screen_3.setFrameShape(QtWidgets.QFrame.Box)
        self.Screen_3.setLineWidth(3)
        self.Screen_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Screen_3.setObjectName("Screen_3")
        self.Screen_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.Screen_1.setGeometry(QtCore.QRect(30, 20, 481, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Screen_1.setFont(font)
        self.Screen_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Screen_1.setObjectName("Screen_1")
        self.Screen_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.Screen_2.setGeometry(QtCore.QRect(30, 100, 481, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Screen_2.setFont(font)
        self.Screen_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Screen_2.setObjectName("Screen_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 554, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Plus_Button.setText(_translate("MainWindow", "Plus"))
        self.Minus_Button.setText(_translate("MainWindow", "Minus"))
        self.Multiply_Button.setText(_translate("MainWindow", "Multiply"))
        self.Divide_Button.setText(_translate("MainWindow", "Divide"))
        self.Screen_3.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
